Adding a description of K-Modulation to OMC methods page
pylhc/pylhc.github.io pull request #34
Opened 2020-12-03 10:41 UTC by mihofer

Fixes #33

2020-12-04 11:55 UTC, JoschD submitted a review, later dismissed

2020-12-05 01:58 UTC, JoschD requested changes

2020-12-05 01:58 UTC, JoschD commented on docs/omc_team/methods.md
> +If these measurements are conducted for two adjacent quadrupoles, the evolution of the $\beta$-function in-between the modulateed quadrupoles can also be infered[^2].
inferred

2020-12-07 09:15 UTC, fsoubelet approved these changes

2020-12-07 10:11 UTC, JoschD approved these changes

2020-12-07 10:13 UTC, merged